title: 腰果文档库（建设中）
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://docs.cashewteam.top

aux_links:
  Template Repository: https://github.com/CashewTeam/cashewdocs/
