title: 腰果文档库
description: 正在建设中~~~
theme: just-the-docs
# Color scheme supports "light" (default) and "dark"
color_scheme: dark
url: https://docs.cashewteam.top
defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

# Enable or disable heading anchors
heading_anchors: true

lang: zh-CN
aux_links:
  腰果映像: https://www.cashewteam.top

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false


# Back to top link
back_to_top: true
back_to_top_text: "Back to top"


plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

