title: 腰果文档库
description: 正在建设中~~~
theme: just-the-docs
# Color scheme supports "light" (default) and "dark"
color_scheme: dark
url: https://docs.cashewteam.top
defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

# Enable or disable heading anchors
heading_anchors: true

lang: zh-CN
aux_links:
  腰果映像: https://www.cashewteam.top

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false


# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

nav_external_links:
  - title: 几何节点中文字典
    url: https://blendercz.top/
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false
  - title: Blender 官方文档
    url: https://docs.blender.org/manual/zh-hans/latest/
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false
  - title: 月离文档库
    url: https://docs.yuelili.com/#/
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false



